project: 
  type: website

website:
  title: "So. FREMONT CAR WASH"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://1ramirez7.github.io/Carwash1
  # repo-actions: [issue] # if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "So. FREMONT CAR WASH©"

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "So. FREMONT CAR WASH"
        file: carwash1.qmd
      - text: "CAR WASH # 2"
        file: carwash2.qmd
      - text: "Laundromat"
        file: laundromat.qmd
      - text: "Car Wash # 3"
        file: carwash3.qmd
      - text: "Laundromat 2"
        file: laundromat2.qmd
      - text: "Laundromat 3"
        file: laundromat3.qmd
      
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: lumen # lumen, morph, materia, sketchy, flatly, litera, simplex, spacelab, united, yeti, cerulean, pandoc, none - more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: lux # darkly, lux, sketchy
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    width: full
    smooth-scroll: true # did not have, maybe delete because I don't see any difference yet, but i'm yet to deploy
